[package]
name = "vermis"
version = "0.5.0"
edition = "2024"
description = "A lossless Luau parser for formatting, linting, and source analysis"
repository = "https://github.com/0hirume/vermis"
license = "MIT"
keywords = ["luau", "parser", "syntax"]
categories = ["development-tools", "parsing"]
include = [
  "/README.md",
  "/src",
  "/tests",
  "/vendor/luau/LICENSE.txt",
  "/vendor/luau/lua_LICENSE.txt",
  "/vendor/luau/tests/conformance/*.lua",
  "/vendor/luau/tests/conformance/*.luau",
]

[dependencies]

[lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

[lints.rust]
deprecated_safe = { level = "deny", priority = -1 }
let_underscore = { level = "deny", priority = -1 }
rust_2018_idioms = { level = "deny", priority = -1 }
unsafe_code = "deny"
unused = { level = "deny", priority = -1 }
warnings = { level = "deny", priority = -1 }
