[tools]
"aqua:Kitware/CMake" = "latest"
"aqua:tombi-toml/tombi" = "latest"
"github:llvm/llvm-project" = "latest"
rust = { version = "nightly", profile = "minimal", components = ["rust-analyzer", "rustfmt", "clippy"] }

[tasks.fuzz]
run = "nu scripts/fuzz.nu"

[tasks.differential]
run = "nu scripts/differential.nu"
