[package]
name = "vermis-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
bstr = "1.13.1"
vermis = { path = ".." }

[[bin]]
name = "lexer"
path = "lexer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "differential"
path = "differential.rs"
test = false
doc = false
bench = false
